export const ICONS_NAME = {
  ENTYPO: {},
  FEATHER: {},
  FONT_AWESOME: {
    REFRESH: 'refresh',
  },
  FONT_AWESOME_5: {},
  IONICONS: {
    IOS_TIMER: 'ios-timer',
    IOS_HOME: 'ios-home',
    IOS_HOME_OUTLINE: 'ios-home-outline',
    BRIEFCASE: 'briefcase',
    BRIEFCASE_OUTLINE: 'briefcase-outline',
    SEARCH: 'search',
    SEARCH_OUTLINE: 'search-outline',
  },
  MATERIAL_COMMUNITY_ICONS: {
    PLUS_CIRCLE_OUTLINE: 'plus-circle-outline',
    CHECK: 'check',
    IMAGE_EDIT: 'image-edit',
    ALERT_OCTAGON: 'alert-octagon',
    CONTENT_SAVE: 'content-save',
    CASH_REGISTER: 'cash-register',
    BELL: 'bell',
    BELL_OUTLINE: 'bell-outline',
    CLOSE_CIRCLE: 'close-circle',
    CLOSE_CIRCLE_OUTLINE: 'close-circle-outline',
    CHECKBOX_MARKED_CIRCLE_OUTLINE: 'checkbox-marked-circle-outline',
    EYE: 'eye',
    EYE_OFF: 'eye-off',
    SHIELD_ACCOUNT: 'shield-account',
    SHIELD_ACCOUNT_OUTLINE: 'shield-account-outline',
  },
  MATERIAL_ICONS: {},
  SIMPLE_LINE_ICONS: {},
};
